language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-opengl-dev zlib1g-dev cppcheck
  - Xvfb :1 &
  - xv -display :1 &
script:
  - export DISPLAY=:1
  - qmake
  - make
  - pushd tests/
  - qmake
  - make
  - for test in `find -executable -type f`; do pushd `dirname $test`; ./`basename $test`||exit 1; popd; done
  - popd
after_script: cppcheck --enable=all -q -Isrc/libtiled `git ls-files src/\*.cpp`
